### ISSUE TITLE
Missing node?

### ISSUE THREAD

**Issue by gerwitz** [geodienst/lighthousemap#7] opened 2022-01-25 08:15 UTC
I noticed my most nearby lighthouse was not represented, so I went to OSM to add it. But it is already there (of course, because the Dutch love OSM). Maybe this is filtered out, but it seems the Overpass API should be returning this:

https://www.openstreetmap.org/node/1375241392

**Comment by jamesscottbrown** [comment] 2022-01-25 09:34
It looks like the issue is that the light sequence is expressed as text in the `description` field, rather than in the `seamark:light:sequence` field (as it is in e.g., [Gilkicker Point](https://www.openstreetmap.org/node/851562493)).

**Comment by gwynna** [comment] 2022-01-25 15:46
Also have a missing lighthouse opposite me! https://www.openstreetmap.org/way/673396687  Newbie so have no idea how to add sorry

**Comment by Asheboy** [comment] 2022-01-26 09:10
@jamesscottbrown is `seamark:light:sequence` the right tag to use? I see [this](https://www.openstreetmap.org/way/361809633) lighthouse has `seamark:light:1:sequence` instead. Should I update it to use `seamark:light:sequence` instead?

**Comment by jamesscottbrown** [comment] 2022-01-26 10:01
The use of numbers like `seamark:light:1:sequence` or `seamark:light:2:sequence` is necessary where there are sector lights (essentially several lights at the same location, each only visible from a certain range of angles) - [this is an example](https://www.openstreetmap.org/node/1543901034) of such a light.

 This this map doesn't currently support sectored lights - see Issue #1.

I don't know if there's any good reason to use `seamark:light:1:sequence` rather than `seamark:light:sequence` if there is only one light to record.

TagInfo provides some information about the use of the [`seamark:light:sequence`](https://taginfo.openstreetmap.org/keys/seamark%3Alight%3Asequence#overview) (8 490 uses) and  [`seamark:light:1:sequence`](https://taginfo.openstreetmap.org/keys/seamark%3Alight%3A1%3Asequence#overview) (5 276 uses) tags.

**Comment by PierreMesure** [comment] 2022-01-27 10:54
I missed you last message @jamesscottbrown but I came to the same conclusions by looking at the code.

So I made a [PR](https://github.com/geodienst/lighthousemap/pull/16) to fetch sectored lights and add basic support for them (basically using the first light's characteristics).

Here's the [result](https://pierremesure.github.io/lighthousemap/). What do you think?

**Comment by gerwitz** [comment] 2022-01-27 20:51
Thanks for the diagnostic, @jamesscottbrown, I've edited this node. After it's been reviewed and I see it reflected here, I think I have a lot of work to do updating Dutch lighthouses.

**Comment by leonmvd** [comment] 2022-02-01 12:27
Thanks a lot @PierreMesure we've merged the PR with some minor changes. If you guys edit the data for these lighthouses in osm it should show up on the map the next day or so

**Closed as completed by leonmvd** 2022-02-01 12:27 UTC
